### ISSUE TITLE
Images do not Popup when being provided by a function

### ISSUE THREAD

**Issue by arekkukula** [sanjayV/ng-image-slider#45]
Hello,
I've came across this problem when developing my own app.
Because of the way I handle URLs, including fetching the URLs from a service, sanitizing them and then mapping onto objects that are valid for `ng-image-slider`, i decided to use a function, only to find out, that the component it's not working as intended, which caused a bit of frustration, but I finally got a reason.

Here's a reproduction repo:
https://github.com/arekkukula/image-slider-repro
and a demo:
https://arekkukula.github.io/image-slider-repro/

Please look into that.  Thanks.

**Comment by sanjayV** [comment]
@arekkukula 
I saw your code.

You should avoid to call function directly from template. Due to Angular change detection this function calling multiple times (100+).

![logs](https://user-images.githubusercontent.com/2578736/75746914-a7575f80-5d41-11ea-9020-2ec35bb53530.png)


For more detail please read following artical: https://medium.com/showpad-engineering/why-you-should-never-use-function-calls-in-angular-template-expressions-e1a50f9c0496

Instead of directly function call in template, you can store images value in scope variable and use that variable for pass images to **ng-image-slider**.

For example:
**In app.component.ts**

```
export class AppComponent implements OnInit {
  imagesArray2: Array<object> = [];

  ngOnInit() {
    this.imagesFunction();
  }

  imagesFunction() {
    this.imagesArray2 = [
      {
        image: "./assets/google-image1.jpg",
        thumbImage: "./assets/google-image1.jpg"
      },
      {
        image: "./assets/google-image2.jpg",
        thumbImage: "./assets/google-image2.jpg"
      }
    ];
  }
} 
```

**In app.component.html**

`<ng-image-slider [images]="imagesArray2"></ng-image-slider>`

**Comment by arekkukula** [comment]
Thanks for responding, the suggestion is on point.

After posting this issue, I started thinking about this and I had a suspicion that it isn't problem with the component itself, but rather with how Angular handles binding. 

With that being said; if implementing some kind of _guard_ that would output error to console when binding `images` to a function wouldn't be much of a problem, that would be much appreciated by future users i think :)
